const words = [
{ english: "Ability", somali: "Awood" },
{ english: "Able", somali: "Kara" },
{ english: "About", somali: "Ku saabsan" },
{ english: "Above", somali: "Kor" },
{ english: "Accept", somali: "Aqbal" },
{ english: "Accident", somali: "Shil" },
{ english: "Account", somali: "Akoon" },
{ english: "Act", somali: "Fal" },
{ english: "Action", somali: "Fal" },
{ english: "Activity", somali: "Hawl" },
{ english: "Add", somali: "Ku dar" },
{ english: "Address", somali: "Cinwaan" },
{ english: "Adult", somali: "Qof weyn" },
{ english: "Adventure", somali: "Tacabur" },
{ english: "Afraid", somali: "Baqaya" },
{ english: "After", somali: "Kadib" },
{ english: "Afternoon", somali: "Galab" },
{ english: "Again", somali: "Mar kale" },
{ english: "Age", somali: "Da'" },
{ english: "Ago", somali: "Hore" },
{ english: "Agree", somali: "Ogolow" },
{ english: "Air", somali: "Hawo" },
{ english: "Airport", somali: "Garoon diyaaradeed" },
{ english: "All", somali: "Dhammaan" },
{ english: "Allow", somali: "Oggolow" },
{ english: "Almost", somali: "Ku dhowaad" },
{ english: "Alone", somali: "Kaligiis" },
{ english: "Already", somali: "Hore" },
{ english: "Also", somali: "Sidoo kale" },
{ english: "Always", somali: "Mar walba" },
{ english: "Amazing", somali: "Cajiib" },
{ english: "America", somali: "Ameerika" },
{ english: "Among", somali: "Dhex" },
{ english: "Amount", somali: "Qaddar" },
{ english: "Animal", somali: "Xayawaan" },
{ english: "Answer", somali: "Jawaab" },
{ english: "Any", somali: "Wax kasta" },
{ english: "Anyone", somali: "Qof kasta" },
{ english: "Anything", somali: "Wax kasta" },
{ english: "Apple", somali: "Tufaax" },
{ english: "April", somali: "Abriil" },
{ english: "Area", somali: "Aag" },
{ english: "Arm", somali: "Gacan" },
{ english: "Around", somali: "Agagaarka" },
{ english: "Arrive", somali: "Imaansho" },
{ english: "Art", somali: "Farshaxan" },
{ english: "Ask", somali: "Weydii" },
{ english: "At", somali: "Jooga" },
{ english: "Attack", somali: "Weerar" },
{ english: "August", somali: "Agoosto" },
{ english: "Aunt", somali: "Eedo" },
{ english: "Author", somali: "Qoraa" },
{ english: "Autumn", somali: "Dayr" },
{ english: "Available", somali: "La heli karo" },
{ english: "Avoid", somali: "Ka fogow" },
{ english: "Away", somali: "Fog" },

{ english: "Baby", somali: "Ilmo" },
{ english: "Back", somali: "Dib" },
{ english: "Bad", somali: "Xun" },
{ english: "Bag", somali: "Boorso" },
{ english: "Ball", somali: "Kubad" },
{ english: "Banana", somali: "Moos" },
{ english: "Bank", somali: "Bangi" },
{ english: "Base", somali: "Saldhig" },
{ english: "Basket", somali: "Dambiil" },
{ english: "Basketball", somali: "Kubadda kolayga" },
{ english: "Bath", somali: "Qubays" },
{ english: "Bathroom", somali: "Musqul" },
{ english: "Beach", somali: "Xeeb" },
{ english: "Bear", somali: "Dibi-duur" },
{ english: "Beautiful", somali: "Qurux badan" },
{ english: "Because", somali: "Sababtoo ah" },
{ english: "Become", somali: "Noqo" },
{ english: "Bed", somali: "Sariir" },
{ english: "Bee", somali: "Shinni" },
{ english: "Before", somali: "Kahor" },
{ english: "Begin", somali: "Bilow" },
{ english: "Behind", somali: "Gadaal" },
{ english: "Believe", somali: "Rumee" },
{ english: "Below", somali: "Hoos" },
{ english: "Best", somali: "Ugu fiican" },
{ english: "Better", somali: "Ka fiican" },
{ english: "Between", somali: "Dhexe" },
{ english: "Bicycle", somali: "Baaskiil" },
{ english: "Big", somali: "Weyn" },
{ english: "Bird", somali: "Shimbir" },
{ english: "Birthday", somali: "Maalinta dhalashada" },
{ english: "Black", somali: "Madow" },
{ english: "Blanket", somali: "Buste" },
{ english: "Blood", somali: "Dhiig" },
{ english: "Blue", somali: "Buluug" },
{ english: "Boat", somali: "Doon" },
{ english: "Body", somali: "Jir" },
{ english: "Book", somali: "Buug" },
{ english: "Boot", somali: "Kabo" },
{ english: "Bottle", somali: "Dhalo" },
{ english: "Box", somali: "Sanduuq" },
{ english: "Boy", somali: "Wiil" },
{ english: "Branch", somali: "Laan" },
{ english: "Brave", somali: "Geesi" },
{ english: "Bread", somali: "Rooti" },
{ english: "Break", somali: "Jebi" },
{ english: "Breakfast", somali: "Quraac" },
{ english: "Bridge", somali: "Buundo" },
{ english: "Bright", somali: "Iftiimaya" },
{ english: "Bring", somali: "Keen" },
{ english: "Brother", somali: "Walaal" },
{ english: "Brown", somali: "Bunni" },
{ english: "Brush", somali: "Burush" },
{ english: "Build", somali: "Dhis" },
{ english: "Building", somali: "Dhisme" },
{ english: "Burn", somali: "Gub" },
{ english: "Bus", somali: "Bas" },
{ english: "Business", somali: "Ganacsi" },
{ english: "Busy", somali: "Mashquul" },
{ english: "Butter", somali: "Subag" },
{ english: "Buy", somali: "Iibso" },
{ english: "By", somali: "Ag" },

{ english: "Cake", somali: "Keeg" },
{ english: "Call", somali: "Wac" },
{ english: "Camera", somali: "Kaamiro" },
{ english: "Camp", somali: "Xero" },
{ english: "Can", somali: "Karaa" },
{ english: "Car", somali: "Gaari" },
{ english: "Card", somali: "Kaarka" },
{ english: "Care", somali: "Daryeel" },
{ english: "Careful", somali: "Taxaddar leh" },
{ english: "Carry", somali: "Qaado" },
{ english: "Cat", somali: "Bisad" },
{ english: "Catch", somali: "Qabso" },
{ english: "Chair", somali: "Kursi" },
{ english: "Chance", somali: "Fursad" },
{ english: "Change", somali: "Beddel" },
{ english: "Cheap", somali: "Jaban" },
{ english: "Check", somali: "Hubi" },
{ english: "Cheese", somali: "Jiis" },
{ english: "Chicken", somali: "Digaag" },
{ english: "Child", somali: "Ilmo" },
{ english: "Children", somali: "Carruur" },
{ english: "Choose", somali: "Dooro" },
{ english: "City", somali: "Magaalo" },
{ english: "Class", somali: "Fasal" },
{ english: "Clean", somali: "Nadiifi" },
{ english: "Clear", somali: "Cad" },
{ english: "Climb", somali: "Fuul" },
{ english: "Clock", somali: "Saacad" },
{ english: "Close", somali: "Xir" },
{ english: "Clothes", somali: "Dharka" },
{ english: "Cloud", somali: "Daruur" },
{ english: "Coat", somali: "Jaakad" },
{ english: "Coffee", somali: "Qaxwo" },
{ english: "Cold", somali: "Qabow" },
{ english: "College", somali: "Kulliyad" },
{ english: "Color", somali: "Midab" },
{ english: "Come", somali: "Kaalay" },
{ english: "Company", somali: "Shirkad" },
{ english: "Computer", somali: "Kombiyuutar" },
{ english: "Cook", somali: "Karso" },
{ english: "Cool", somali: "Qabow" },
{ english: "Copy", somali: "Nuqul" },
{ english: "Corner", somali: "Gees" },
{ english: "Correct", somali: "Sax" },
{ english: "Cost", somali: "Qiimo" },
{ english: "Cotton", somali: "Cudbi" },
{ english: "Country", somali: "Dal" },
{ english: "Course", somali: "Koorsada" },
{ english: "Cow", somali: "Lo'" },
{ english: "Create", somali: "Abuur" },
{ english: "Cross", somali: "Gudub" },
{ english: "Cry", somali: "Ooy" },
{ english: "Cup", somali: "Koob" },
{ english: "Cut", somali: "Jar" },
{ english: "Daily", somali: "Maalinle" },
{ english: "Dance", somali: "Qoob ka ciyaar" },
{ english: "Danger", somali: "Khatar" },
{ english: "Dark", somali: "Madow" },
{ english: "Date", somali: "Taariikh" },
{ english: "Daughter", somali: "Gabar" },
{ english: "Day", somali: "Maalin" },
{ english: "Dead", somali: "Dhintay" },
{ english: "Dear", somali: "Gacaliye" },
{ english: "December", somali: "Diseembar" },
{ english: "Decide", somali: "Go'aanso" },
{ english: "Deep", somali: "Qoto dheer" },
{ english: "Delicious", somali: "Macaan" },
{ english: "Describe", somali: "Sharax" },
{ english: "Desk", somali: "Miis" },
{ english: "Develop", somali: "Horumari" },
{ english: "Dictionary", somali: "Qaamuus" },
{ english: "Die", somali: "Dhimo" },
{ english: "Different", somali: "Kala duwan" },
{ english: "Difficult", somali: "Adag" },
{ english: "Dinner", somali: "Casho" },
{ english: "Dirty", somali: "Wasakh" },
{ english: "Discover", somali: "Soo hel" },
{ english: "Discuss", somali: "Ka dood" },
{ english: "Dish", somali: "Saxan" },
{ english: "Do", somali: "Samee" },
{ english: "Doctor", somali: "Dhakhtar" },
{ english: "Dog", somali: "Ey" },
{ english: "Dollar", somali: "Doollar" },
{ english: "Door", somali: "Albaab" },
{ english: "Down", somali: "Hoos" },
{ english: "Draw", somali: "Sawir" },
{ english: "Dream", somali: "Riyo" },
{ english: "Dress", somali: "Dhar" },
{ english: "Drink", somali: "Cab" },
{ english: "Drive", somali: "Wad" },
{ english: "Driver", somali: "Darawal" },
{ english: "Drop", somali: "Dhibic" },
{ english: "Dry", somali: "Qallalan" },
{ english: "Duck", somali: "Bataakh" },

{ english: "Each", somali: "Mid kasta" },
{ english: "Ear", somali: "Dheg" },
{ english: "Early", somali: "Hore" },
{ english: "Earth", somali: "Dhul" },
{ english: "East", somali: "Bariga" },
{ english: "Easy", somali: "Fudud" },
{ english: "Eat", somali: "Cun" },
{ english: "Education", somali: "Waxbarasho" },
{ english: "Egg", somali: "Ukun" },
{ english: "Eight", somali: "Siddeed" },
{ english: "Eighteen", somali: "Siddeed iyo toban" },
{ english: "Eighty", somali: "Siddeetan" },
{ english: "Elephant", somali: "Maroodi" },
{ english: "Eleven", somali: "Kow iyo toban" },
{ english: "Else", somali: "Kale" },
{ english: "Empty", somali: "Madhan" },
{ english: "End", somali: "Dhammaad" },
{ english: "Enemy", somali: "Cadow" },
{ english: "Enjoy", somali: "Ku raaxayso" },
{ english: "Enough", somali: "Ku filan" },
{ english: "Enter", somali: "Gal" },
{ english: "Equal", somali: "Is le'eg" },
{ english: "Even", somali: "Xitaa" },
{ english: "Evening", somali: "Fiid" },
{ english: "Ever", somali: "Waligii" },
{ english: "Every", somali: "Mid kasta" },
{ english: "Everyone", somali: "Qof walba" },
{ english: "Everything", somali: "Wax walba" },
{ english: "Example", somali: "Tusaale" },
{ english: "Excellent", somali: "Heer sare" },
{ english: "Excuse", somali: "Raalli noqo" },
{ english: "Exercise", somali: "Jimicsi" },
{ english: "Expensive", somali: "Qaali" },
{ english: "Experience", somali: "Khibrad" },
{ english: "Explain", somali: "Sharax" },
{ english: "Eye", somali: "Indho" },
{ english: "Face", somali: "Waji" },
{ english: "Fact", somali: "Xaqiiqo" },
{ english: "Factory", somali: "Warshad" },
{ english: "Fail", somali: "Fashil" },
{ english: "Fall", somali: "Dhac" },
{ english: "Family", somali: "Qoys" },
{ english: "Famous", somali: "Caan" },
{ english: "Far", somali: "Fog" },
{ english: "Farm", somali: "Beer" },
{ english: "Farmer", somali: "Beeraley" },
{ english: "Fast", somali: "Dheereeya" },
{ english: "Fat", somali: "Buuran" },
{ english: "Father", somali: "Aabe" },
{ english: "Fear", somali: "Cabsi" },
{ english: "February", somali: "Febraayo" },
{ english: "Feel", somali: "Dareen" },
{ english: "Festival", somali: "Bandhig" },
{ english: "Few", somali: "Yar" },
{ english: "Field", somali: "Beer" },
{ english: "Fight", somali: "Dagaal" },
{ english: "Fill", somali: "Buuxi" },
{ english: "Film", somali: "Filim" },
{ english: "Find", somali: "Hel" },
{ english: "Fine", somali: "Fiican" },
{ english: "Finger", somali: "Far" },
{ english: "Finish", somali: "Dhamee" },
{ english: "Fire", somali: "Dab" },
{ english: "Fish", somali: "Kalluun" },
{ english: "Five", somali: "Shan" },
{ english: "Flag", somali: "Calan" },
{ english: "Floor", somali: "Sagxad" },
{ english: "Flower", somali: "Ubax" },
{ english: "Fly", somali: "Duul" },
{ english: "Food", somali: "Cunto" },
{ english: "Foot", somali: "Cag" },
{ english: "Football", somali: "Kubadda cagta" },
{ english: "For", somali: "Loogu talagalay" },
{ english: "Forest", somali: "Kayn" },
{ english: "Forget", somali: "Illow" },
{ english: "Fork", somali: "Fargeeto" },
{ english: "Friend", somali: "Saaxiib" },
{ english: "From", somali: "Ka yimid" },
{ english: "Front", somali: "Hore" },
{ english: "Fruit", somali: "Miro" },
{ english: "Full", somali: "Buuxa" },
{ english: "Funny", somali: "Qosol badan" },
{ english: "Future", somali: "Mustaqbal" },

{ english: "Game", somali: "Ciyaar" },
{ english: "Garden", somali: "Beer" },
{ english: "Gas", somali: "Gaas" },
{ english: "Gate", somali: "Albaab" },
{ english: "General", somali: "Guud" },
{ english: "Gentle", somali: "Dabacsan" },
{ english: "Get", somali: "Hel" },
{ english: "Gift", somali: "Hadiyad" },
{ english: "Girl", somali: "Gabar" },
{ english: "Give", somali: "Sii" },
{ english: "Glass", somali: "Muraayad" },
{ english: "Go", somali: "Tag" },
{ english: "Goat", somali: "Ri" },
{ english: "God", somali: "Ilaah" },
{ english: "Gold", somali: "Dahab" },
{ english: "Good", somali: "Wanaagsan" },
{ english: "Government", somali: "Dowlad" },
{ english: "Grandfather", somali: "Awoowe" },
{ english: "Grandmother", somali: "Ayeeyo" },
{ english: "Grass", somali: "Caws" },
{ english: "Great", somali: "Weyn" },
{ english: "Green", somali: "Cagaar" },
{ english: "Ground", somali: "Dhul" },
{ english: "Group", somali: "Koox" },
{ english: "Grow", somali: "Kor" },
{ english: "Guess", somali: "Qiyaas" },
{ english: "Guest", somali: "Marti" },
{ english: "Guide", somali: "Hage" },
{ english: "Gun", somali: "Qori" },
{ english: "Gym", somali: "Goob jimicsi" },
{ english: "Habit", somali: "Caado" },
{ english: "Hair", somali: "Timo" },
{ english: "Half", somali: "Badh" },
{ english: "Hall", somali: "Hool" },
{ english: "Hand", somali: "Gacan" },
{ english: "Happy", somali: "Faraxsan" },
{ english: "Hard", somali: "Adag" },
{ english: "Hat", somali: "Koofiyad" },
{ english: "Have", somali: "Leh" },
{ english: "He", somali: "Isaga" },
{ english: "Head", somali: "Madax" },
{ english: "Health", somali: "Caafimaad" },
{ english: "Hear", somali: "Maqal" },
{ english: "Heart", somali: "Wadne" },
{ english: "Heavy", somali: "Culus" },
{ english: "Help", somali: "Caawi" },
{ english: "Her", somali: "Iyadeeda" },
{ english: "Here", somali: "Halkan" },
{ english: "Hide", somali: "Qari" },
{ english: "High", somali: "Sare" },
{ english: "Hill", somali: "Buur yar" },
{ english: "Him", somali: "Isaga" },
{ english: "His", somali: "Kiisa" },
{ english: "History", somali: "Taariikh" },
{ english: "Hold", somali: "Qabo" },
{ english: "Hole", somali: "Dalool" },
{ english: "Holiday", somali: "Fasax" },
{ english: "Home", somali: "Guri" },
{ english: "Hope", somali: "Rajo" },
{ english: "Horse", somali: "Faras" },
{ english: "Hospital", somali: "Isbitaal" },
{ english: "Hot", somali: "Kulul" },
{ english: "Hotel", somali: "Huteel" },
{ english: "Hour", somali: "Saacad" },
{ english: "House", somali: "Guri" },
{ english: "How", somali: "Sidee" },
{ english: "Hungry", somali: "Gaajaysan" },
{ english: "Husband", somali: "Nin" },

{ english: "Ice", somali: "Baraf" },
{ english: "Idea", somali: "Fikrad" },
{ english: "If", somali: "Haddii" },
{ english: "Important", somali: "Muhiim" },
{ english: "Improve", somali: "Horumari" },
{ english: "In", somali: "Gudaha" },
{ english: "Include", somali: "Ku dar" },
{ english: "Information", somali: "Macluumaad" },
{ english: "Inside", somali: "Gudaha" },
{ english: "Interest", somali: "Xiise" },
{ english: "Internet", somali: "Internet" },
{ english: "Into", somali: "Gudaha" },
{ english: "Introduce", somali: "Soo bandhig" },
{ english: "Island", somali: "Jasiirad" },
{ english: "It", somali: "Waxay" },
{ english: "Item", somali: "Shay" },

{ english: "Jacket", somali: "Jaakad" },
{ english: "January", somali: "Janaayo" },
{ english: "Job", somali: "Shaqo" },
{ english: "Join", somali: "Ku biir" },
{ english: "Journey", somali: "Safar" },
{ english: "Joy", somali: "Farxad" },
{ english: "Judge", somali: "Garsoore" },
{ english: "Juice", somali: "Casiir" },
{ english: "July", somali: "Luulyo" },
{ english: "Jump", somali: "Bood" },
{ english: "June", somali: "Juun" },
{ english: "Junior", somali: "Yar" },
{ english: "Just", somali: "Kaliya" },
{ english: "Justice", somali: "Caddaalad" },
{ english: "Ability", somali: "Karti" },
{ english: "Absent", somali: "Maqan" },
{ english: "Absolute", somali: "Dhamaystiran" },
{ english: "Academic", somali: "Waxbarasho" },
{ english: "Access", somali: "Helitaan" },
{ english: "Accurate", somali: "Sax ah" },
{ english: "Achieve", somali: "Gaadh" },
{ english: "Across", somali: "Dhinac ilaa dhinac" },
{ english: "Active", somali: "Firfircoon" },
{ english: "Actually", somali: "Dhab ahaantii" },
{ english: "Adapt", somali: "La qabsasho" },
{ english: "Additional", somali: "Dheeraad ah" },
{ english: "Admire", somali: "Qaddari" },
{ english: "Advance", somali: "Horumar" },
{ english: "Advantage", somali: "Faa'iido" },
{ english: "Advice", somali: "Talo" },
{ english: "Afford", somali: "Awoodi karo" },
{ english: "Agent", somali: "Wakiil" },
{ english: "Alarm", somali: "Digniin" },
{ english: "Album", somali: "Albam" },
{ english: "Alive", somali: "Nool" },
{ english: "Alphabet", somali: "Alifbeeto" },
{ english: "Ancient", somali: "Qadiimi" },
{ english: "Angry", somali: "Xanaaqsan" },
{ english: "Announce", somali: "Ku dhawaaq" },
{ english: "Anxiety", somali: "Walwal" },
{ english: "Apartment", somali: "Guri dabaq ah" },
{ english: "Appear", somali: "Muuqdo" },
{ english: "Apply", somali: "Codso" },
{ english: "Approach", somali: "Hab" },
{ english: "Approve", somali: "Ansixi" },
{ english: "Argument", somali: "Dood" },
{ english: "Army", somali: "Ciidan" },
{ english: "Arrange", somali: "Habee" },
{ english: "Arrest", somali: "Xir" },
{ english: "Article", somali: "Maqaal" },
{ english: "Artist", somali: "Farshaxanle" },
{ english: "Artificial", somali: "Macmal" },
{ english: "Ash", somali: "Dambas" },
{ english: "Assist", somali: "Caawi" },
{ english: "Athlete", somali: "Ciyaaryahan" },
{ english: "Atmosphere", somali: "Jawiga" },
{ english: "Attack", somali: "Weerar" },
{ english: "Attend", somali: "Ka qaybgal" },
{ english: "Attention", somali: "Feejignaan" },
{ english: "Attract", somali: "Soo jiid" },
{ english: "Audience", somali: "Dhagaystayaal" },
{ english: "Average", somali: "Celcelis" },
{ english: "Award", somali: "Abaalmarin" },
{ english: "Awful", somali: "Aad u xun" },
{ english: "Balance", somali: "Dheellitir" },
{ english: "Barber", somali: "Timo-jare" },
{ english: "Basic", somali: "Aasaasi" },
{ english: "Behavior", somali: "Dhaqan" },
{ english: "Belong", somali: "Leeyahay" },
{ english: "Benefit", somali: "Faa'iido" },
{ english: "Beyond", somali: "Ka baxsan" },
{ english: "Billion", somali: "Bilyan" },
{ english: "Blank", somali: "Madhan" },
{ english: "Blind", somali: "Indho la'" },
{ english: "Block", somali: "Xannib" },
{ english: "Blood Pressure", somali: "Cadaadiska dhiigga" },
{ english: "Board", somali: "Loox" },
{ english: "Borrow", somali: "Amaahso" },
{ english: "Boss", somali: "Madaxa" },
{ english: "Bottom", somali: "Hoosta" },
{ english: "Brain", somali: "Maskax" },
{ english: "Brand", somali: "Summad" },
{ english: "Breath", somali: "Neef" },
{ english: "Broadcast", somali: "Baahin" },
{ english: "Bullet", somali: "Rasaas" },
{ english: "Burger", somali: "Burger" },
{ english: "Cab", somali: "Tagsi" },
{ english: "Cable", somali: "Fiilo" },
{ english: "Calculator", somali: "Mashiinka xisaabta" },
{ english: "Calendar", somali: "Jadwal" },
{ english: "Campaign", somali: "Ol'ole" },
{ english: "Cancer", somali: "Kansar" },
{ english: "Candidate", somali: "Musharrax" },
{ english: "Capital", somali: "Caasimad" },
{ english: "Captain", somali: "Kabtan" },
{ english: "Career", somali: "Xirfad" },
{ english: "Carpet", somali: "Roog" },
{ english: "Cartoon", somali: "Kartuun" },
{ english: "Cash", somali: "Lacag caddaan ah" },
{ english: "Castle", somali: "Qasri" },
{ english: "Cause", somali: "Sabab" },
{ english: "Celebrate", somali: "Dabaaldeg" },
{ english: "Cell", somali: "Unug" },
{ english: "Century", somali: "Qarni" },
{ english: "Certificate", somali: "Shahaado" },
{ english: "Chain", somali: "Silsilad" },
{ english: "Challenge", somali: "Caqabad" },
{ english: "Character", somali: "Dabeecad" },
{ english: "Charge", somali: "Lacag qaadid" },
{ english: "Charity", somali: "Samafal" },
{ english: "Chart", somali: "Jaantus" },
{ english: "Cheaply", somali: "Si jaban" },
{ english: "Cheer", somali: "Dhiirrigeli" },
{ english: "Chemical", somali: "Kiimiko" },
{ english: "Chest", somali: "Laab" },
{ english: "Chief", somali: "Madax" },
{ english: "Chicken Soup", somali: "Maraq digaag" },
{ english: "Chief Executive", somali: "Maamule guud" },
{ english: "Choice", somali: "Doorasho" },
{ english: "Citizen", somali: "Muwaadin" },
{ english: "Civil", somali: "Madani" },
{ english: "Claim", somali: "Sheegasho" },
{ english: "Classic", somali: "Qadiimi" },
{ english: "Climate", somali: "Cimilo" },
{ english: "Clinic", somali: "Rug caafimaad" },
{ english: "Coach", somali: "Tababare" },
{ english: "Coal", somali: "Dhuxul" },
{ english: "Coast", somali: "Xeeb" },
{ english: "Code", somali: "Kood" },
{ english: "Collect", somali: "Ururi" },
{ english: "Comfort", somali: "Raaxo" },
{ english: "Command", somali: "Amar" },
{ english: "Comment", somali: "Faallo" },
{ english: "Commercial", somali: "Ganacsi" },
{ english: "Committee", somali: "Guddi" },
{ english: "Common", somali: "Caadi" },
{ english: "Communication", somali: "Isgaarsiin" },
{ english: "Community", somali: "Bulsho" },
{ english: "Compare", somali: "Isbarbar dhig" },
{ english: "Competition", somali: "Tartan" },
{ english: "Complete", somali: "Dhammaystir" },
{ english: "Complex", somali: "Adag" },
{ english: "Condition", somali: "Xaalad" },
{ english: "Conference", somali: "Shir" },
{ english: "Confidence", somali: "Kalsooni" },
{ english: "Confirm", somali: "Xaqiiji" },
{ english: "Connect", somali: "Xiriir" },
{ english: "Connection", somali: "Xiriir" },
{ english: "Construction", somali: "Dhismaha" },
{ english: "Contact", somali: "Xiriir" },
{ english: "Content", somali: "Nuxur" },
{ english: "Contest", somali: "Tartan" },
{ english: "Continue", somali: "Sii wad" },
{ english: "Control", somali: "Xakamee" },
{ english: "Conversation", somali: "Wadahadal" },
{ english: "Cooker", somali: "Makiinadda karinta" },
{ english: "Cookie", somali: "Buskud" },
{ english: "Corner Shop", somali: "Dukaan yar" },
{ english: "Correctly", somali: "Si sax ah" },
{ english: "Cotton Farm", somali: "Beer cudbi" },
{ english: "Council", somali: "Golaha" },
{ english: "Courage", somali: "Geesinimo" },
{ english: "Court", somali: "Maxkamad" },
{ english: "Cover", somali: "Dabool" },
{ english: "Craft", somali: "Farsamo" },
{ english: "Crash", somali: "Shil" },
{ english: "Creative", somali: "Hal-abuur leh" },
{ english: "Creature", somali: "Makhluuq" },
{ english: "Credit", somali: "Deyn" },
{ english: "Crime", somali: "Dambi" },
{ english: "Critical", somali: "Muhiim" },
{ english: "Culture", somali: "Dhaqan" },
{ english: "Current", somali: "Hadda" },
{ english: "Custom", somali: "Caado" },
{ english: "Decision", somali: "Go'aan" },
{ english: "Deliver", somali: "Gaarsii" },
{ english: "Demand", somali: "Dalab" },
{ english: "Department", somali: "Waax" },
{ english: "Depend", somali: "Ku tiirsanow" },
{ english: "Design", somali: "Naqshad" },
{ english: "Destroy", somali: "Burburi" },
{ english: "Detail", somali: "Faahfaahin" },
{ english: "Developing", somali: "Horumaraya" },
{ english: "Device", somali: "Qalab" },
{ english: "Dialogue", somali: "Wadahadal" },
{ english: "Digital", somali: "Dijitaal" },
{ english: "Direct", somali: "Toos" },
{ english: "Director", somali: "Agaasime" },
{ english: "Discipline", somali: "Anshax" },
{ english: "Discount", somali: "Qiimo dhimis" },
{ english: "Disease Control", somali: "Xakamaynta cudurrada" },
{ english: "Display", somali: "Bandhig" },
{ english: "Distance", somali: "Masaafad" },
{ english: "District", somali: "Degmo" },
{ english: "Document", somali: "Dukumenti" },
{ english: "Domestic", somali: "Gudaha dalka" },
{ english: "Double", somali: "Laba-laab" },
{ english: "Download File", somali: "Soo dejiso fayl" },
{ english: "Drama", somali: "Riwaayad" },
{ english: "Drawing", somali: "Sawirid" },
{ english: "Driver License", somali: "Ruqsadda wadista" },
{ english: "Dust", somali: "Boor" },
{ english: "Duty", somali: "Waajib" },
{ english: "Dynamic", somali: "Firfircoon" },
{ english: "Eager", somali: "Xiisaynaya" },
{ english: "Earn", somali: "Kasbo" },
{ english: "Economic", somali: "Dhaqaale" },
{ english: "Editor", somali: "Tifaftire" },
{ english: "Effect", somali: "Saameyn" },
{ english: "Effort", somali: "Dadaal" },
{ english: "Election", somali: "Doorasho" },
{ english: "Electric", somali: "Koronto" },
{ english: "Electronic", somali: "Elektaroonig" },
{ english: "Element", somali: "Curiye" },
{ english: "Email", somali: "Iimayl" },
{ english: "Emergency", somali: "Xaalad degdeg ah" },
{ english: "Employee", somali: "Shaqaale" },
{ english: "Employer", somali: "Loo-shaqeeye" },
{ english: "Energy", somali: "Tamar" },
{ english: "Engineer", somali: "Injineer" },
{ english: "Engine", somali: "Matoor" },
{ english: "English", somali: "Af-Ingiriisi" },
{ english: "Entrance", somali: "Irid" },
{ english: "Environment", somali: "Deegaan" },
{ english: "Equipment", somali: "Qalab" },
{ english: "Escape", somali: "Ka baxso" },
{ english: "Essential", somali: "Muhiim" },
{ english: "Establish", somali: "Aasaas" },
{ english: "Estimate", somali: "Qiyaas" },
{ english: "Event", somali: "Dhacdo" },
{ english: "Evidence", somali: "Caddeyn" },
{ english: "Exact", somali: "Sax ah" },
{ english: "Exchange", somali: "Isweydaarsi" },
{ english: "Excited", somali: "Faraxsan" },
{ english: "Exhibit", somali: "Bandhig" },
{ english: "Exist", somali: "Jir" },
{ english: "Exit", somali: "Ka bax" },
{ english: "Expand", somali: "Ballaadhi" },
{ english: "Expect", somali: "Filo" },
{ english: "Expert", somali: "Khabiir" },
{ english: "Export", somali: "Dhoofin" },
{ english: "Express", somali: "Muuji" },
{ english: "Extra", somali: "Dheeraad" },
{ english: "Factory Worker", somali: "Shaqaale warshad" },
{ english: "Failure", somali: "Fashil" },
{ english: "Faith", somali: "Iimaan" },
{ english: "False", somali: "Been" },
{ english: "Fan", somali: "Marawaxad" },
{ english: "Fare", somali: "Qiimaha safarka" },
{ english: "Fashion", somali: "Moodo" },
{ english: "Feature", somali: "Astaan" },
{ english: "Federal", somali: "Federaal" },
{ english: "Female", somali: "Dhedig" },
{ english: "Fence", somali: "Dayr" },
{ english: "Ferry", somali: "Doon rakaab" },
{ english: "Fever", somali: "Qandho" },
{ english: "Fiction", somali: "Sheeko mala-awaal" },
{ english: "File", somali: "Fayl" },
{ english: "Finance", somali: "Maaliyad" },
{ english: "Financial", somali: "Maaliyadeed" },
{ english: "Finger Print", somali: "Faraha" },
{ english: "Fitness", somali: "Jirdhis" },
{ english: "Fix", somali: "Dayactir" },
{ english: "Flash", somali: "Iftiin degdeg ah" },
{ english: "Flight", somali: "Duulimaad" },
{ english: "Flood", somali: "Daad" },
{ english: "Focus", somali: "Diiradda saar" },
{ english: "Follow", somali: "Raac" },
{ english: "Force", somali: "Xoog" },
{ english: "Foreign", somali: "Ajnabi" },
{ english: "Forever", somali: "Weligeed" },
{ english: "Form", somali: "Foom" },
{ english: "Formal", somali: "Rasmi" },
{ english: "Forward", somali: "Hore u soco" },
{ english: "Freedom", somali: "Xorriyad" },
{ english: "Freeze", somali: "Barafee" },
{ english: "Fresh", somali: "Cusub" },
{ english: "Friendly", somali: "Saaxiibtinimo leh" },
{ english: "Fuel", somali: "Shidaal" },
{ english: "Function", somali: "Shaqo" },
{ english: "Furniture", somali: "Alaabta guriga" },
{ english: "Future Plan", somali: "Qorshaha mustaqbalka" },
{ english: "Galaxy", somali: "Koox xiddigo" },
{ english: "Garage", somali: "Garaash" },
{ english: "Garbage", somali: "Qashin" },
{ english: "Garlic", somali: "Toon" },
{ english: "Gather", somali: "Ururi" },
{ english: "Gender", somali: "Jinsi" },
{ english: "Generate", somali: "Soo saar" },
{ english: "Generation", somali: "Jiil" },
{ english: "Generator", somali: "Matoor koronto" },
{ english: "Genius", somali: "Maskax badan" },
{ english: "Gentleman", somali: "Mudane" },
{ english: "Geography", somali: "Juqraafi" },
{ english: "Gesture", somali: "Tilmaan" },
{ english: "Ghost", somali: "Ruux" },
{ english: "Giant", somali: "Rafaa" },
{ english: "Global", somali: "Caalami" },
{ english: "Glove", somali: "Galoof" },
{ english: "Goal", somali: "Hadaf" },
{ english: "Golden", somali: "Dahabi" },
{ english: "Goods", somali: "Alaabo" },
{ english: "Graduate", somali: "Qalin-jabiye" },
{ english: "Grammar", somali: "Naxwe" },
{ english: "Graphic", somali: "Sawir-gacmeed" },
{ english: "Greeting", somali: "Salaan" },
{ english: "Grocery", somali: "Raashin" },
{ english: "Guarantee", somali: "Dammaanad" },
{ english: "Guard", somali: "Ilaaliye" },
{ english: "Guideline", somali: "Tilmaame" },
{ english: "Guilty", somali: "Dambiile" },
{ english: "Guitar", somali: "Gitaar" },
{ english: "Gymnasium", somali: "Hool jimicsi" },
{ english: "Habitual", somali: "Caado u leh" },
{ english: "Hammer", somali: "Dubbe" },
{ english: "Handle", somali: "Gacan-qabsi" },
{ english: "Harbor", somali: "Deked" },
{ english: "Harvest", somali: "Goosasho" },
{ english: "Hazard", somali: "Khatar" },
{ english: "Headline", somali: "Cinwaan" },
{ english: "Headquarters", somali: "Xarunta dhexe" },
{ english: "Heal", somali: "Bogsii" },
{ english: "Healthcare", somali: "Daryeel caafimaad" },
{ english: "Healthy", somali: "Caafimaad qaba" },
{ english: "Hearing", somali: "Maqal" },
{ english: "Heat", somali: "Kulayl" },
{ english: "Height", somali: "Dherer" },
{ english: "Helmet", somali: "Koofiyadda badbaadada" },
{ english: "Helpful", somali: "Waxtar leh" },
{ english: "Hero", somali: "Geesi" },
{ english: "Hidden", somali: "Qarsoon" },
{ english: "Highway", somali: "Waddo weyn" },
{ english: "Hire", somali: "Shaqaaleysiin" },
{ english: "Historic", somali: "Taariikhi" },
{ english: "Honest", somali: "Daacad" },
{ english: "Honor", somali: "Sharaf" },
{ english: "Hook", somali: "Qabato" },
{ english: "Horizontal", somali: "Jiif ah" },
{ english: "Host", somali: "Martigeliye" },
{ english: "Human", somali: "Aadanaha" },
{ english: "Humble", somali: "Is-hoosaysiin leh" },
{ english: "Humor", somali: "Kaftan" },
{ english: "Hunt", somali: "Ugaarsi" },
{ english: "Hurry", somali: "Degdeg" },
{ english: "Hurt", somali: "Dhaawac" },
{ english: "Hygiene", somali: "Nadaafad" },
{ english: "Ice Cream", somali: "Jalaato" },
{ english: "Identify", somali: "Aqoonso" },
{ english: "Identity", somali: "Aqoonsi" },
{ english: "Ignore", somali: "Iska indho tir" },
{ english: "Illegal", somali: "Sharci darro" },
{ english: "Imagine", somali: "Malo awaal" },
{ english: "Immediate", somali: "Isla markiiba" },
{ english: "Impact", somali: "Saameyn" },
{ english: "Import", somali: "Soo dejin" },
{ english: "Impossible", somali: "Aan suurtagal ahayn" },
{ english: "Improve Skills", somali: "Horumari xirfadaha" },
{ english: "Income", somali: "Dakhli" },
{ english: "Increase", somali: "Kordhi" },
{ english: "Independent", somali: "Madax-bannaan" },
{ english: "Industry", somali: "Warshado" },
{ english: "Infection", somali: "Caabuq" },
{ english: "Influence", somali: "Saamee" },
{ english: "Ingredient", somali: "Maaddo" },
{ english: "Injury", somali: "Dhaawac" },
{ english: "Innovation", somali: "Hal-abuur" },
{ english: "Input", somali: "Gelinta" },
{ english: "Insect", somali: "Cayayaan" },
{ english: "Inspect", somali: "Baadh" },
{ english: "Inspire", somali: "Dhiirrigeli" },
{ english: "Install", somali: "Rakib" },
{ english: "Instruction", somali: "Tilmaamo" },
{ english: "Insurance", somali: "Caymis" },
{ english: "Intelligence", somali: "Sirdoon" },
{ english: "Intelligent", somali: "Caqli badan" },
{ english: "Intend", somali: "Ujeeddo yeelo" },
{ english: "International", somali: "Caalami" },
{ english: "Interview", somali: "Wareysi" },
{ english: "Invent", somali: "Ikhtiraac" },
{ english: "Invitation", somali: "Casuumaad" },
{ english: "Invite", somali: "Casuum" },
{ english: "Iron", somali: "Bir" },
{ english: "Issue", somali: "Arrin" },
{ english: "Jail", somali: "Xabsi" },
{ english: "Jewelry", somali: "Dahab iyo qurxin" },
{ english: "Journal", somali: "Joornaal" },
{ english: "Journalist", somali: "Suxufi" },
{ english: "Judge Court", somali: "Garsoore maxkamadeed" },
{ english: "Keyboard", somali: "Kiiboodh" },
{ english: "Kid", somali: "Ilmo" },
{ english: "Kidney", somali: "Kelyo" },
{ english: "Kilogram", somali: "Kiiloogaraam" },
{ english: "Kind", somali: "Naxariis leh" },
{ english: "King", somali: "Boqor" },
{ english: "Kitchen", somali: "Jikada" },
{ english: "Knife", somali: "Mindi" },
{ english: "Knowledge", somali: "Aqoon" },
{ english: "Known", somali: "La yaqaan" },
{ english: "Label", somali: "Summad" },
{ english: "Labor", somali: "Shaqo" },
{ english: "Laboratory", somali: "Shaybaar" },
{ english: "Lack", somali: "La'aan" },
{ english: "Lake", somali: "Haro" },
{ english: "Language", somali: "Luqad" },
{ english: "Laptop", somali: "Laptop" },
{ english: "Large", somali: "Weyn" },
{ english: "Last", somali: "Ugu dambeeya" },
{ english: "Laugh", somali: "Qosol" },
{ english: "Law", somali: "Sharci" },
{ english: "Lawyer", somali: "Qareen" },
{ english: "Leader", somali: "Hoggaamiye" },
{ english: "Leadership", somali: "Hoggaamin" },
{ english: "Learning", somali: "Barasho" },
{ english: "Lecture", somali: "Muxaadaro" },
{ english: "Legal", somali: "Sharci ah" },
{ english: "Legend", somali: "Halyeey" },
{ english: "Library", somali: "Maktabad" },
{ english: "License", somali: "Ruqsad" },
{ english: "Lifeguard", somali: "Badbaadiye" },
{ english: "Lifetime", somali: "Nolosha oo dhan" },
{ english: "Lightning", somali: "Hillaac" },
{ english: "Limit", somali: "Xad" },
{ english: "Link", somali: "Xiriiriye" },
{ english: "Liquid", somali: "Dareere" },
{ english: "Literature", somali: "Suugaan" },
{ english: "Local", somali: "Maxalli" },
{ english: "Location", somali: "Goob" },
{ english: "Logic", somali: "Mantiq" },
{ english: "Loyal", somali: "Daacad" },
{ english: "Luxury", somali: "Raaxo" },
{ english: "Machine", somali: "Mashiin" },
{ english: "Magazine", somali: "Majallad" },
{ english: "Magic", somali: "Sixir" },
{ english: "Major", somali: "Muhiim" },
{ english: "Manager", somali: "Maamule" },
{ english: "Manufacture", somali: "Soo saar" },
{ english: "Market", somali: "Suuq" },
{ english: "Marriage", somali: "Guur" },
{ english: "Material", somali: "Qalab" },
{ english: "Maximum", somali: "Ugu badan" },
{ english: "Measure", somali: "Cabir" },
{ english: "Mechanic", somali: "Farsamo yaqaan" },
{ english: "Media", somali: "Warbaahin" },
{ english: "Medical", somali: "Caafimaad" },
{ english: "Medicine", somali: "Daawo" },
{ english: "Meeting", somali: "Shir" },
{ english: "Memory", somali: "Xusuus" },
{ english: "Message", somali: "Farriin" },
{ english: "Metal", somali: "Bir" },
{ english: "Method", somali: "Hab" },
{ english: "Middle", somali: "Dhexe" },
{ english: "Military", somali: "Ciidan" },
{ english: "Mineral", somali: "Macdan" },
{ english: "Minimum", somali: "Ugu yar" },
{ english: "Minister", somali: "Wasiir" },
{ english: "Minute", somali: "Daqiiqad" },
{ english: "Mirror", somali: "Muraayad" },
{ english: "Mission", somali: "Hawlgal" },
{ english: "Mobile", somali: "Moobil" },
{ english: "Model", somali: "Nooc" },
{ english: "Modern", somali: "Casri" },
{ english: "Monitor", somali: "Kormeere" },
{ english: "Mountain", somali: "Buur" },
{ english: "Movement", somali: "Dhaqdhaqaaq" },
{ english: "Museum", somali: "Matxaf" },
{ english: "Music", somali: "Muusig" },
{ english: "Nation", somali: "Qaran" },
{ english: "National", somali: "Qaran ah" },
{ english: "Native", somali: "Dhalad" },
{ english: "Natural", somali: "Dabiici" },
{ english: "Necessary", somali: "Lama huraan" },
{ english: "Neighbor", somali: "Deris" },
{ english: "Network", somali: "Shabakad" },
{ english: "Newspaper", somali: "Wargeys" },
{ english: "Normal", somali: "Caadi" },
{ english: "Notice", somali: "Ogeysiis" },
{ english: "Novel", somali: "Sheeko dheer" },
{ english: "Number", somali: "Lambar" },
{ english: "Object", somali: "Shay" },
{ english: "Objective", somali: "Ujeeddo" },
{ english: "Observe", somali: "U fiirso" },
{ english: "Occasion", somali: "Munaasabad" },
{ english: "Ocean", somali: "Badweyn" },
{ english: "Offer", somali: "Bixin" },
{ english: "Office", somali: "Xafiis" },
{ english: "Official", somali: "Rasmi" },
{ english: "Operation", somali: "Hawlgal" },
{ english: "Opinion", somali: "Aragti" },
{ english: "Opportunity", somali: "Fursad" },
{ english: "Order", somali: "Dalab" },
{ english: "Organization", somali: "Urur" },
{ english: "Original", somali: "Asal" },
{ english: "Outcome", somali: "Natiijo" },
{ english: "Outdoor", somali: "Dibadda" },
{ english: "Output", somali: "Wax-soo-saar" },
{ english: "Owner", somali: "Milkiile" },
{ english: "Package", somali: "Baakad" },
{ english: "Pain", somali: "Xanuun" },
{ english: "Painter", somali: "Rinjiile" },
{ english: "Paper", somali: "Warqad" },
{ english: "Paragraph", somali: "Faqrad" },
{ english: "Parking", somali: "Baarkin" },
{ english: "Partner", somali: "Lammaane" },
{ english: "Passenger", somali: "Rakaab" },
{ english: "Passport", somali: "Baasaboor" },
{ english: "Patient", somali: "Bukaan" },
{ english: "Pattern", somali: "Qaab" },
{ english: "Payment", somali: "Lacag bixin" },
{ english: "Peace", somali: "Nabad" },
{ english: "Performance", somali: "Waxqabad" },
{ english: "Permission", somali: "Ogolaansho" },
{ english: "Personality", somali: "Shakhsiyad" },
{ english: "Photograph", somali: "Sawir" },
{ english: "Physical", somali: "Jireed" },
{ english: "Phrase", somali: "Weedh" },
{ english: "Pilot", somali: "Duuliye" },
{ english: "Pipe", somali: "Tuubo" },
{ english: "Planet", somali: "Meeraha" },
{ english: "Plastic", somali: "Balaastiig" },
{ english: "Platform", somali: "Madal" },
{ english: "Player", somali: "Ciyaaryahan" },
{ english: "Pleasure", somali: "Farxad" },
{ english: "Plenty", somali: "Badan" },
{ english: "Pocket", somali: "Jeeb" },
{ english: "Poem", somali: "Gabay" },
{ english: "Poet", somali: "Abwaan" },
{ english: "Poison", somali: "Sun" },
{ english: "Police", somali: "Booliis" },
{ english: "Policy", somali: "Siyaasad" },
{ english: "Polite", somali: "Akhlaaq leh" },
{ english: "Politics", somali: "Siyaasad" },
{ english: "Pollution", somali: "Wasakhow" },
{ english: "Population", somali: "Dadweyne" },
{ english: "Port", somali: "Deked" },
{ english: "Position", somali: "Boos" },
{ english: "Positive", somali: "Wanaagsan" },
{ english: "Possibility", somali: "Suurtagalnimo" },
{ english: "Post", somali: "Boosto" },
{ english: "Pot", somali: "Dheri" },
{ english: "Potato", somali: "Baradho" },
{ english: "Powerful", somali: "Awood badan" },
{ english: "Practical", somali: "Wax ku ool ah" },
{ english: "Practice", somali: "Tababar" },
{ english: "Praise", somali: "Ammaan" },
{ english: "Prayer", somali: "Ducada" },
{ english: "Precious", somali: "Qaali ah" },
{ english: "Predict", somali: "Saadaali" },
{ english: "Prefer", somali: "Doorbiday" },
{ english: "Prepare", somali: "Diyaari" },
{ english: "Present", somali: "Hadiyad" },
{ english: "President", somali: "Madaxweyne" },
{ english: "Press", somali: "Riix" },
{ english: "Pressure", somali: "Cadaadis" },
{ english: "Prevent", somali: "Ka hortag" },
{ english: "Price", somali: "Qiime" },
{ english: "Primary", somali: "Aasaasi" },
{ english: "Prince", somali: "Amiir" },
{ english: "Princess", somali: "Amiirad" },
{ english: "Principal", somali: "Maamule dugsi" },
{ english: "Print", somali: "Daabac" },
{ english: "Prison", somali: "Xabsi" },
{ english: "Private", somali: "Gaar ah" },
{ english: "Prize", somali: "Abaalmarin" },
{ english: "Process", somali: "Habraac" },
{ english: "Produce", somali: "Soo saar" },
{ english: "Product", somali: "Wax soo saar" },
{ english: "Production", somali: "Soo saarid" },
{ english: "Professional", somali: "Xirfadle" },
{ english: "Professor", somali: "Bare sare" },
{ english: "Program", somali: "Barnaamij" },
{ english: "Progress", somali: "Horumar" },
{ english: "Project", somali: "Mashruuc" },
{ english: "Promise", somali: "Ballan" },
{ english: "Promote", somali: "Kor u qaad" },
{ english: "Proof", somali: "Caddeyn" },
{ english: "Property", somali: "Hanti" },
{ english: "Protect", somali: "Ilaali" },
{ english: "Proud", somali: "Ku faan" },
{ english: "Provide", somali: "Bixi" },
{ english: "Public", somali: "Dadweyne" },
{ english: "Publish", somali: "Daabac" },
{ english: "Pull", somali: "Jiid" },
{ english: "Punish", somali: "Ciqaab" },
{ english: "Purchase", somali: "Iibso" },
{ english: "Pure", somali: "Saafi" },
{ english: "Purpose", somali: "Ujeeddo" },
{ english: "Push", somali: "Riix" },
{ english: "Quality", somali: "Tayo" },
{ english: "Quantity", somali: "Tiro" },
{ english: "Quarter", somali: "Rubuc" },
{ english: "Questionnaire", somali: "Su'aalo-waraysi" },
{ english: "Queue", somali: "Saf" },
{ english: "Quickly", somali: "Si degdeg ah" },
{ english: "Quiet", somali: "Aamusnaan" },
{ english: "Quotation", somali: "Xigasho" },
{ english: "Race", somali: "Tartan" },
{ english: "Railway", somali: "Tareen jidkiisa" },
{ english: "Raise", somali: "Kor u qaad" },
{ english: "Range", somali: "Kala duwanaansho" },
{ english: "Rapid", somali: "Degdeg badan" },
{ english: "Rare", somali: "Naadir" },
{ english: "Reaction", somali: "Falcelin" },
{ english: "Reader", somali: "Akhriste" },
{ english: "Reality", somali: "Xaqiiqo" },
{ english: "Reasonable", somali: "Macquul" },
{ english: "Receipt", somali: "Rasiid" },
{ english: "Receive", somali: "Hel" },
{ english: "Recent", somali: "Dhawaan" },
{ english: "Recognize", somali: "Aqoonso" },
{ english: "Recommend", somali: "Ku tali" },
{ english: "Record", somali: "Diiwaan" },
{ english: "Recover", somali: "Ka soo kabso" },
{ english: "Reduce", somali: "Yaree" },
{ english: "Reflect", somali: "Ka tarjum" },
{ english: "Refuse", somali: "Diid" },
{ english: "Region", somali: "Gobol" },
{ english: "Register", somali: "Diiwaangeli" },
{ english: "Regular", somali: "Joogto ah" },
{ english: "Reject", somali: "Diid" },
{ english: "Relation", somali: "Xiriir" },
{ english: "Relationship", somali: "Xiriirka" },
{ english: "Relative", somali: "Qaraabo" },
{ english: "Relax", somali: "Nasasho" },
{ english: "Release", somali: "Sii daa" },
{ english: "Relief", somali: "Nasasho" },
{ english: "Religion", somali: "Diin" },
{ english: "Remain", somali: "Har" },
{ english: "Remember", somali: "Xasuuso" },
{ english: "Remove", somali: "Ka saar" },
{ english: "Repair", somali: "Dayactir" },
{ english: "Repeat", somali: "Ku celi" },
{ english: "Replace", somali: "Beddel" },
{ english: "Reply", somali: "Jawaab" },
{ english: "Report", somali: "Warbixin" },
{ english: "Represent", somali: "Matal" },
{ english: "Request", somali: "Codsi" },
{ english: "Require", somali: "U baahan" },
{ english: "Research", somali: "Cilmi baaris" },
{ english: "Respect", somali: "Ixtiraam" },
{ english: "Respond", somali: "Ka jawaab" },
{ english: "Responsibility", somali: "Mas'uuliyad" },
{ english: "Rest", somali: "Nasasho" },
{ english: "Restaurant", somali: "Maqaayad" },
{ english: "Result", somali: "Natiijo" },
{ english: "Return", somali: "Soo noqo" },
{ english: "Review", somali: "Dib u eegis" },
{ english: "Reward", somali: "Abaalmarin" },
{ english: "Rice", somali: "Bariis" },
{ english: "Rich", somali: "Taajir" },
{ english: "Ride", somali: "Raac" },
{ english: "Ring", somali: "Faraanti" },
{ english: "Rise", somali: "Kac" },
{ english: "River", somali: "Webi" },
{ english: "Road", somali: "Waddo" },
{ english: "Robot", somali: "Robot" },
{ english: "Rock", somali: "Dhagax" },
{ english: "Role", somali: "Door" },
{ english: "Roof", somali: "Saqaf" },
{ english: "Room", somali: "Qol" },
{ english: "Root", somali: "Xidid" },
{ english: "Rope", somali: "Xadhig" },
{ english: "Rose", somali: "Ubax Rose" },
{ english: "Rough", somali: "Qalafsan" },
{ english: "Round", somali: "Wareegsan" },
{ english: "Route", somali: "Jid" },
{ english: "Rule", somali: "Xeer" },
{ english: "Runner", somali: "Orodyahan" },
{ english: "Rural", somali: "Miyi" },
{ english: "Safe", somali: "Ammaan" },
{ english: "Safety", somali: "Badbaado" },
{ english: "Sail", somali: "Shiraac" },
{ english: "Salary", somali: "Mushahar" },
{ english: "Sale", somali: "Iib" },
{ english: "Salt", somali: "Cusbo" },
{ english: "Sample", somali: "Muunad" },
{ english: "Sand", somali: "Ciid" },
{ english: "Satellite", somali: "Dayax-gacmeed" },
{ english: "Save", somali: "Badbaadi" },
{ english: "Scale", somali: "Miisaan" },
{ english: "School", somali: "Dugsi" },
{ english: "Science", somali: "Saynis" },
{ english: "Scientist", somali: "Saynisyahan" },
{ english: "Screen", somali: "Shaashad" },
{ english: "Search", somali: "Raadi" },
{ english: "Season", somali: "Xilli" },
{ english: "Seat", somali: "Kursi" },
{ english: "Second", somali: "Labaad" },
{ english: "Secret", somali: "Sir" },
{ english: "Section", somali: "Qayb" },
{ english: "Security", somali: "Amniga" },
{ english: "Seed", somali: "Abuur" },
{ english: "Select", somali: "Dooro" },
{ english: "Self", somali: "Nafta" },
{ english: "Sell", somali: "Iibi" },
{ english: "Send", somali: "Dir" },
{ english: "Senior", somali: "Waayeel" },
{ english: "Sense", somali: "Dareen" },
{ english: "Sentence", somali: "Jumlad" },
{ english: "Separate", somali: "Kala saar" },
{ english: "Serious", somali: "Halis" },
{ english: "Serve", somali: "Adeeg" },
{ english: "Service", somali: "Adeeg" },
{ english: "Session", somali: "Kulan" },
{ english: "Set", somali: "Deji" },
{ english: "Settle", somali: "Deg" },
{ english: "Shadow", somali: "Hoos" },
{ english: "Shake", somali: "Rux" },
{ english: "Shape", somali: "Qaab" },
{ english: "Share", somali: "Wadaag" },
{ english: "Sharp", somali: "Af badan" },
{ english: "Sheep", somali: "Ido" },
{ english: "Shelf", somali: "Shelf" },
{ english: "Shell", somali: "Qolof" },
{ english: "Shield", somali: "Gaashaan" },
{ english: "Shine", somali: "Iftiim" },
{ english: "Ship", somali: "Markab" },
{ english: "Shock", somali: "Naxdin" },
{ english: "Shoot", somali: "Rasaas rid" },
{ english: "Shop", somali: "Dukaan" },
{ english: "Shopping", somali: "Wax iibsasho" },
{ english: "Short", somali: "Gaaban" },
{ english: "Should", somali: "Waa in" },
{ english: "Shoulder", somali: "Garab" },
{ english: "Shout", somali: "Qayli" },
{ english: "Show", somali: "Muuji" },
{ english: "Shower", somali: "Qubays" },
{ english: "Shut", somali: "Xir" },
{ english: "Sick", somali: "Xanuunsan" },
{ english: "Side", somali: "Dhinac" },
{ english: "Sight", somali: "Aragti" },
{ english: "Sign", somali: "Calaamad" },
{ english: "Signal", somali: "Astaamo" },
{ english: "Silence", somali: "Aamusnaan" },
{ english: "Silent", somali: "Aamusan" },
{ english: "Silver", somali: "Qalin" },
{ english: "Simple", somali: "Fudud" },
{ english: "Since", somali: "Tan iyo" },
{ english: "Sing", somali: "Hees" },
{ english: "Singer", somali: "Fannaan" },
{ english: "Single", somali: "Keliya" },
{ english: "Sink", somali: "Saxanka dhaqidda" },
{ english: "Sister", somali: "Walaash" },
{ english: "Sit", somali: "Fadhiiso" },
{ english: "Situation", somali: "Xaalad" },
{ english: "Size", somali: "Cabbir" },
{ english: "Skill", somali: "Xirfad" },
{ english: "Skin", somali: "Maqaar" },
{ english: "Sky", somali: "Cir" },
{ english: "Sleep", somali: "Hurdo" },
{ english: "Slice", somali: "Jeex" },
{ english: "Slow", somali: "Gaabis" },
{ english: "Small", somali: "Yar" },
{ english: "Smart", somali: "Xariif" },
{ english: "Smile", somali: "Dhoolla-caddee" },
{ english: "Smoke", somali: "Qiiq" },
{ english: "Smooth", somali: "Siman" },
{ english: "Snake", somali: "Mas" },
{ english: "Snow", somali: "Baraf" },
{ english: "Soap", somali: "Saabuun" },
{ english: "Social", somali: "Bulsho" },
{ english: "Society", somali: "Bulshada" },
{ english: "Sock", somali: "Sharabaad" },
{ english: "Soft", somali: "Jilicsan" },
{ english: "Soil", somali: "Ciid" },
{ english: "Soldier", somali: "Askari" },
{ english: "Solution", somali: "Xal" },
{ english: "Solve", somali: "Xalli" },
{ english: "Someone", somali: "Qof" },
{ english: "Something", somali: "Wax" },
{ english: "Sometimes", somali: "Mararka qaar" },
{ english: "Son", somali: "Wiil" },
{ english: "Song", somali: "Hees" },
{ english: "Soon", somali: "Dhawaan" },
{ english: "Sorry", somali: "Waan ka xumahay" },
{ english: "Sound", somali: "Cod" },
{ english: "Soup", somali: "Maraq" },
{ english: "South", somali: "Koonfur" },
{ english: "Space", somali: "Meel bannaan" },
{ english: "Speak", somali: "Hadal" },
{ english: "Speaker", somali: "Afhayeen" },
{ english: "Special", somali: "Gaar ah" },
{ english: "Speech", somali: "Khudbad" },
{ english: "Speed", somali: "Xawaare" },
{ english: "Spell", somali: "Higaadi" },
{ english: "Spend", somali: "Bixi" },
{ english: "Spider", somali: "Caaro" },
{ english: "Spirit", somali: "Ruux" },
{ english: "Sport", somali: "Isboorti" },
{ english: "Spring", somali: "Guga" },
{ english: "Square", somali: "Afar-gees" },
{ english: "Stable", somali: "Deggan" },
{ english: "Staff", somali: "Shaqaale" },
{ english: "Stage", somali: "Madal" },
{ english: "Stair", somali: "Jaranjaro" },
{ english: "Stamp", somali: "Shaabad" },
{ english: "Stand", somali: "Istaag" },
{ english: "Star", somali: "Xiddig" },
{ english: "Start", somali: "Bilow" },
{ english: "State", somali: "Gobol" },
{ english: "Station", somali: "Saldhig" },
{ english: "Stay", somali: "Joog" },
{ english: "Steal", somali: "Xado" },
{ english: "Steam", somali: "Uumi" },
{ english: "Steel", somali: "Bir adag" },
{ english: "Step", somali: "Tallaabo" },
{ english: "Stick", somali: "Ul" },
{ english: "Still", somali: "Weli" },
{ english: "Stone", somali: "Dhagax" },
{ english: "Stop", somali: "Jooji" },
{ english: "Store", somali: "Dukaan" },
{ english: "Storm", somali: "Duufaan" },
{ english: "Story", somali: "Sheeko" },
{ english: "Straight", somali: "Toosan" },
{ english: "Strange", somali: "Yaab leh" },
{ english: "Street", somali: "Waddo" },
{ english: "Strong", somali: "Xooggan" },
{ english: "Student", somali: "Arday" },
{ english: "Study", somali: "Waxbarasho" },
{ english: "Success", somali: "Guul" },
{ english: "Sugar", somali: "Sonkor" },
{ english: "Suggest", somali: "Soo jeedi" },
{ english: "Summer", somali: "Xagaa" },
{ english: "Sun", somali: "Qorrax" },
{ english: "Sunday", somali: "Axad" },
{ english: "Support", somali: "Taageer" },
{ english: "Sure", somali: "Huban" },
{ english: "Surface", somali: "Dusha" },
{ english: "Surprise", somali: "Yaab" },
{ english: "Surround", somali: "Ku wareegsan" },
{ english: "Survey", somali: "Sahan" },
{ english: "Survive", somali: "Badbaad" },
{ english: "Sweet", somali: "Macaan" },
{ english: "Swim", somali: "Dabaal" },
{ english: "Switch", somali: "Beddel" },
{ english: "System", somali: "Nidaam" },
{ english: "Table", somali: "Miis" },
{ english: "Tablet", somali: "Kiniin" },
{ english: "Tail", somali: "Dabo" },
{ english: "Take", somali: "Qaado" },
{ english: "Talent", somali: "Hibo" },
{ english: "Talk", somali: "Hadal" },
{ english: "Tall", somali: "Dheer" },
{ english: "Tank", somali: "Haanta" },
{ english: "Target", somali: "Bartilmaameed" },
{ english: "Task", somali: "Hawl" },
{ english: "Taste", somali: "Dhadhan" },
{ english: "Taxi", somali: "Tagsi" },
{ english: "Teacher", somali: "Macallin" },
{ english: "Team", somali: "Koox" },
{ english: "Technology", somali: "Tiknoolajiyad" },
{ english: "Telephone", somali: "Telefoon" },
{ english: "Television", somali: "Telefishan" },
{ english: "Temperature", somali: "Heerkul" },
{ english: "Temple", somali: "Macbad" },
{ english: "Temporary", somali: "Ku meel gaar" },
{ english: "Tennis", somali: "Tenis" },
{ english: "Term", somali: "Erey" },
{ english: "Terrible", somali: "Aad u xun" },
{ english: "Test", somali: "Imtixaan" },
{ english: "Text", somali: "Qoraal" },
{ english: "Thank", somali: "Mahadnaq" },
{ english: "Theater", somali: "Masrax" },
{ english: "Theme", somali: "Mawduuc" },
{ english: "Theory", somali: "Aragti" },
{ english: "Thick", somali: "Qaro weyn" },
{ english: "Thin", somali: "Khafiif" },
{ english: "Thing", somali: "Shay" },
{ english: "Think", somali: "Fakar" },
{ english: "Third", somali: "Saddexaad" },
{ english: "Thought", somali: "Fikir" },
{ english: "Thread", somali: "Dun" },
{ english: "Threat", somali: "Hanjabaad" },
{ english: "Throw", somali: "Tuur" },
{ english: "Thursday", somali: "Khamiis" },
{ english: "Ticket", somali: "Tigidh" },
{ english: "Tiger", somali: "Shabeel" },
{ english: "Time", somali: "Waqti" },
{ english: "Tip", somali: "Talo" },
{ english: "Tire", somali: "Taayir" },
{ english: "Today", somali: "Maanta" },
{ english: "Together", somali: "Wadajir" },
{ english: "Tomorrow", somali: "Berri" },
{ english: "Tongue", somali: "Carrab" },
{ english: "Tool", somali: "Qalab" },
{ english: "Tooth", somali: "Ilig" },
{ english: "Topic", somali: "Mawduuc" },
{ english: "Torch", somali: "Toosh" },
{ english: "Total", somali: "Wadarta" },
{ english: "Touch", somali: "Taabo" },
{ english: "Tour", somali: "Dalxiis" },
{ english: "Tourist", somali: "Dalxiise" },
{ english: "Toward", somali: "Dhanka" },
{ english: "Tower", somali: "Munaarad" },
{ english: "Town", somali: "Magaalo yar" },
{ english: "Toy", somali: "Alaabta carruurtu ku ciyaarto" },
{ english: "Track", somali: "Raad" },
{ english: "Trade", somali: "Ganacsi" },
{ english: "Tradition", somali: "Dhaqan" },
{ english: "Traffic", somali: "Gaadiid" },
{ english: "Train", somali: "Tareen" },
{ english: "Trainer", somali: "Tababare" },
{ english: "Training", somali: "Tababar" },
{ english: "Translate", somali: "Turjun" },
{ english: "Transport", somali: "Gaadiid" },
{ english: "Travel", somali: "Safar" },
{ english: "Treasure", somali: "Hanti qaali ah" },
{ english: "Tree", somali: "Geed" },
{ english: "Trip", somali: "Socdaal" },
{ english: "Trouble", somali: "Dhibaato" },
{ english: "Truck", somali: "Baabuur weyn" },
{ english: "Trust", somali: "Aamin" },
{ english: "Truth", somali: "Run" },
{ english: "Try", somali: "Isku day" },
{ english: "Tuesday", somali: "Talaado" },
{ english: "Turn", somali: "Leexo" },
{ english: "Type", somali: "Nooc" },
{ english: "Typical", somali: "Caadi ah" },
{ english: "Umbrella", somali: "Dallad" },
{ english: "Uncle", somali: "Adeer" },
{ english: "Understand", somali: "Faham" },
{ english: "University", somali: "Jaamacad" },
{ english: "Uniform", somali: "Labbis" },
{ english: "Union", somali: "Urur" },
{ english: "Unique", somali: "Gaar ah" },
{ english: "Unit", somali: "Cutub" },
{ english: "United", somali: "Midoobay" },
{ english: "Universal", somali: "Caalami" },
{ english: "Unknown", somali: "Aan la aqoon" },
{ english: "Unlock", somali: "Fur" },
{ english: "Until", somali: "Ilaa" },
{ english: "Update", somali: "Cusboonaysii" },
{ english: "Upgrade", somali: "Kor u qaad" },
{ english: "Upload", somali: "Soo geli" },
{ english: "Upper", somali: "Sare" },
{ english: "Upset", somali: "Murugaysan" },
{ english: "Urban", somali: "Magaalo" },
{ english: "Urgent", somali: "Degdeg ah" },
{ english: "Use", somali: "Isticmaal" },
{ english: "Useful", somali: "Faa'iido leh" },
{ english: "User", somali: "Isticmaale" },
{ english: "Usually", somali: "Badanaa" },
{ english: "Vacation", somali: "Fasax" },
{ english: "Valley", somali: "Dooxo" },
{ english: "Value", somali: "Qiime" },
{ english: "Variable", somali: "Isbeddelaya" },
{ english: "Vegetable", somali: "Khudaar" },
{ english: "Vehicle", somali: "Gaari" },
{ english: "Version", somali: "Nooc" },
{ english: "Very", somali: "Aad" },
{ english: "Victory", somali: "Guul" },
{ english: "Video", somali: "Fiidiyow" },
{ english: "Village", somali: "Tuulo" },
{ english: "Violence", somali: "Rabshad" },
{ english: "Visit", somali: "Booqo" },
{ english: "Visitor", somali: "Marti" },
{ english: "Voice", somali: "Cod" },
{ english: "Vote", somali: "Codee" },
{ english: "Vowel", somali: "Shaqal" },
{ english: "Wait", somali: "Sug" },
{ english: "Wake", somali: "Soo toos" },
{ english: "Walk", somali: "Soco" },
{ english: "Wall", somali: "Darbiga" },
{ english: "Wallet", somali: "Boorsada lacagta" },
{ english: "Want", somali: "Rab" },
{ english: "War", somali: "Dagaal" },
{ english: "Warm", somali: "Diiran" },
{ english: "Warn", somali: "Digniin sii" },
{ english: "Wash", somali: "Dhaq" },
{ english: "Waste", somali: "Qashin" },
{ english: "Watch", somali: "Daawo" },
{ english: "Water", somali: "Biyo" },
{ english: "Wave", somali: "Mowjad" },
{ english: "Weak", somali: "Daciif" },
{ english: "Wealth", somali: "Hanti" },
{ english: "Weapon", somali: "Hub" },
{ english: "Wear", somali: "Xidho" },
{ english: "Weather", somali: "Cimilo" },
{ english: "Wedding", somali: "Aroos" },
{ english: "Week", somali: "Toddobaad" },
{ english: "Weight", somali: "Miisaan" },
{ english: "Welcome", somali: "Soo dhowow" },
{ english: "West", somali: "Galbeed" },
{ english: "Wet", somali: "Qoyan" },
{ english: "Whale", somali: "Nibiri" },
{ english: "Wheel", somali: "Taayir" },
{ english: "Where", somali: "Halkee" },
{ english: "While", somali: "Inta lagu jiro" },
{ english: "Whisper", somali: "Hoos u hadal" },
{ english: "White", somali: "Caddaan" },
{ english: "Whole", somali: "Dhan" },
{ english: "Wide", somali: "Ballaaran" },
{ english: "Wife", somali: "Xaaska" },
{ english: "Wild", somali: "Duurjoog" },
{ english: "Will", somali: "Dooni" },
{ english: "Win", somali: "Guuleyso" },
{ english: "Wind", somali: "Dabayl" },
{ english: "Window", somali: "Daaqad" },
{ english: "Winner", somali: "Guuleyste" },
{ english: "Winter", somali: "Jiilaal" },
{ english: "Wire", somali: "Silig" },
{ english: "Wise", somali: "Xikmad leh" },
{ english: "Wish", somali: "Rabitaan" },
{ english: "Woman", somali: "Haweeney" },
{ english: "Wonder", somali: "Yaab" },
{ english: "Wood", somali: "Qoryo" },
{ english: "Word", somali: "Erey" },
{ english: "Work", somali: "Shaqo" },
{ english: "Worker", somali: "Shaqaale" },
{ english: "World", somali: "Adduun" },
{ english: "Worry", somali: "Walwal" },
{ english: "Worth", somali: "Qiimo leh" },
{ english: "Write", somali: "Qor" },
{ english: "Writer", somali: "Qoraa" },
{ english: "Wrong", somali: "Qalad" },
{ english: "Yard", somali: "Barxad" },
{ english: "Year", somali: "Sanad" },
{ english: "Yellow", somali: "Jaalle" },
{ english: "Young", somali: "Dhallinyaro" },
{ english: "Youth", somali: "Dhallinyaro" },
{ english: "Zero", somali: "Eber" },
{ english: "Zone", somali: "Aag" },
];